### ISSUE TITLE
License is GPL3

### ISSUE THREAD

**Issue by sbingner** [tihmstar/libtakeover#1]
With a GPL3 license, nothing can link your library.  If that was your intention, that's fine but just wanted to identify the issue.  If you wanted to permit other things to use the library you may want to consider re-licensing GPL2, LGPL, or even BSD/MIT?

**Comment by sbingner** [comment]
Also wanted to make sure that you are aware that due to the "electronic cancer" way GPL3 works this would make libgeneral and anything that uses it also have to be GPL3 if you want to stick with GPL3

**Comment by tihmstar** [comment]
Done
